* ИП
** Зарегистритьваться в исполкоме
Cвободы, 10 (паспорт, фотку, заявление) UPD: адрес изменился
*** Паспорт
*** Фотку 3x4
*** Заявление
заявление могут заполнить в BSB банке, что двумя этажами выше, за 10 руб
** Через 2-3 дня забрать документы
* Банк - BSB
** Открыть счета
не дожидаясь готовности свидетельства, можно открыть счета (у меня USD + BYN, если будешь работать с Европой - то и EUR)
** Получить флешку с ключом
** Проверить доступ к ibank.bsb.by
Попытаться создать и подписать документы в Virtualbox/Windows.
Документы нужно заполнять, подписывать ключом и отправлять в банк.
Типичному программеру нужно 3 документа:
*** Документ 41
Сведения о поступлении валютных средств - нужно заполнять в течение 5 дней после получения валюты
*** Документ 62
Платежное поручение с конверсией - когда продаешь валюту
*** Документ 60
Перечисление на карточку
** Подключить мобильный app BSB
*** Написать заявление на включение 2факторки
у BSB есть мобильная прилага для ИП, в которой можно подписывать документы через СМС-верификацию. Можно прямо в банке попросить подрубить прилагу и написать заявление на включение двухфакторки
** Заказать карточки
заодно заказать в BSB карточек. Как минимум BYN, чтобы вынимать деньги

* Налоговая
документы готовы, идешь в налоговую своего района, ищешь инспектора, отвечающего за твою улицу. Тип деятельности (62010 Деятельность в области компьютерного программирования по ОКЭД)
** Задания от инспектора
*** Купить книгу учета проверок
*** Купить папку типа "дело"
*** Заполнить заяление на УСН
УСН - упрощенная система налогообложения - лимит выручки в год ~85K евро. Если будет больше - не переходить а курить магуалы по единому налогу. Хотя в 2019м должны поднять лимиты и там будет ваще где-то тыщ 100 уе в год. его следует заполнить в течение 20 дней после регистрации ИП. Иначе придется платить не 5% налог, а 14 единый
*** Получить USB-ключи и сертификаты в удостоверяющем центре
сертификаты выдаются на диске, диск можно переписать на флешку в почти любом печатном центре
** Регистрация в portal.nalog.gov.by
снова VirtualBox, регистрация в личном кабинете налоговой (portal.nalog.gov.by) или в eDeclaration. В общем, убедиться, что или портал работает или eDeclaration работает (это отдельное развлечение, win7,8,10, dll hell, кириллица, проброс USB, установка своих сертификатов и цепочки до корневого (их штук 4-6))

* Можно получать деньги
** Инвойс
формируешь инвойс с уникальным номером (он будет фигурировать в отчетности) за каждый месяц работы / выполненную часть, высылаешь заказчику. Инфу о счете можно скопипастить с сайта BSB, у меня инфа о счете выглядит так:

#+BEGIN_VERSE
Наименование: Индивидуальный предприниматель Колесень Александр Викторович УНП 1XXXXXXXX5
Юридический адрес: РЕСПУБЛИКА БЕЛАРУСЬ; , г. Минск, 2XXXX3, ул. Минеральная, д. 2, кв. 25
Расчетный счет: BY16UNBS3XXXXXXXXXXXXXXXX933
Дополнительная информация к счету

Банк получателя: ЗАО «БСБ Банк», Республика Беларусь
УНП банка получателя: 807000069
BIC код банка получателя: UNBSBY2X
#+END_VERSE

** Ждешь прихода денег
Если деньги не пришли в течение пары дней, уточняешь у заказчика, скорей всего он забыл указать intermediary bank

** Деньги пришли
*** Сформировать, подписать, отправить документ 41
там фигурирует номер инвойса
*** Сформировать, подписать, отправить документ 62
Там фигурирует курс, так что сначала надо позвонить в банк узнать курс или - я пользуюсь "Валютным маклером" в ibank.bsb.by, это тупо чатик:
#+BEGIN_VERSE
 - здравствуйте чем могу помочь
 - продаю валюту, 1000уе
 - могу предложить вам курс 2.13
 - ок я согласен
#+END_VERSE
*** Сформировать, подписать, отправить документ 60

* Налоги
** УСН
уплачивается поквартально до ~20 числа месяца, следующего за отчетным кварталом
*** Заполнить декларацию на portal.nalog.gov.by
*** Подождать, пока ее подпишет инспектор
*** Оплатить через ЕРИП
(Налоги->УСН->по УНП)

** ФСЗН
*** Раз в год до 1 марта через ЕРИП
Оплачивается раз в год через ЕРИП, согласно периодам, в которых осуществлял деятельность
При расчете ФСЗН, если не работал какую-то часть месяца, учитываются все дни месяца, не только рабочие или нет

*** TODO Форма ПУ-3 - подать раз в год до 1 апреля
там Virtualbox, винда, приложение для формирования ПУ-3, приложение для подписи, portal.ssf.gov.by
**** Атрибутивный сертификат для ФСЗН
сходить в любую налоговую, заказать себе атрибутивный сертификат для ФСЗН
***** Анкета - сведения об ИП 2 копии
https://nces.by/wp-content/uploads/perechen-ip.docx
***** Квитанция(!) об оплате счет-фактуры
https://nces.by/wp-content/uploads/6.2.43.pdf
распечатать и отдать в банк, ничего не заполняя)
***** Копия квитанции об оплате
***** Копия свидетельства о регистрации
***** Копия свидетельства о постановке на учет
